version: "3.9"

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      APP_ENV: development
      LOG_LEVEL: debug
      DATABASE_URL: postgresql+asyncpg://metid:metid@db:5432/metid
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    depends_on:
      - db
      - redis
    volumes:
      - ./app:/app/app   # hot-reload in dev

  worker:
    build: .
    command: celery -A app.workers.celery_app worker --loglevel=info --concurrency=2
    environment:
      APP_ENV: development
      DATABASE_URL: postgresql+asyncpg://metid:metid@db:5432/metid
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: metid
      POSTGRES_PASSWORD: metid
      POSTGRES_DB: metid
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pgdata:
